# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

python:
  version: 3.6
  install:
    - sphinx-autoapi
    - sphinx-rtd-theme
    - requirements: 
        - docs/requirements.txt    
    - method: pip