language: python

python:
  - '3.6'

compiler:
  - g++

cache:
  ccache: true
  pip: true

before_install:
  - pip install coveralls
  - pip install python-coveralls

install:
# Install SLRealizer dependencies
  - "pip install -e . -r requirements.txt"

script:
  - coverage run --source h0rton setup.py test

after_success:
  - codecov
  - coveralls