language: python

python:
  - '3.6'

compiler:
  - g++

cache:
  ccache: true
  pip: true

before_install:
  - pip install -q coveralls
  - git clone https://github.com/sibirrer/hierArc.git
  - cd hierArc
  - pip install -e .
  - cd ..

install:
# Install SLRealizer dependencies
  - "pip install -e . -r requirements.txt"

script:
  - coverage run --source=h0rton -m pytest h0rton/tests/

after_success:
  - codecov
  - coveralls