language: python

python:
  - '3.6'

compiler:
  - g++

cache:
  ccache: true
  pip: true

before_install:
  - pip install -q coveralls
  - git clone https://github.com/sibirrer/hierArc.git
  - cd hierArc
  - pip install -e . -r requirements.txt
  - cd ..
  - sudo apt-get install gfortran
  - git clone https://github.com/sibirrer/fastell4py.git
  - cd fastell4py
  - python setup.py install
  - cd ..

install:
  - pip install -e . -U -r requirements.txt

script:
  - coverage run --source=h0rton -m pytest h0rton/tests/

after_success:
  - codecov
  - coveralls